<?php

    $SUCCESS = 1;
    // GENERIC_ERRORS
    $NO_SUCH_URI = -1;
    $INVALID_PARAMS = $NO_SUCH_URI - 1;
    // DB_ERRORS
    $DB_DOES_NOT_EXISTS = $INVALID_PARAMS - 1;
    $DB_CREATION = $DB_DOES_NOT_EXISTS - 1;
    $DB_NO_CONNECTION = $DB_CREATION - 1;
    // TABLE_ERRORS
    $TABLE_DOES_NOT_EXISTS = $DB_NO_CONNECTION - 1;
    // MYSQL_ERRORS
    $MYSQL_THROW_ERROR = $TABLE_DOES_NOT_EXISTS - 1;
    $MYSQL_NO_CONNECTION = $MYSQL_THROW_ERROR - 1;
    // SQL ERRORS
    $DATABASE_CREATION_ERROR = $MYSQL_NO_CONNECTION - 1;
    $TABLE_CREATION_ERROR = $DATABASE_CREATION_ERROR - 1;
    $CURRENT_DATABASE_CHANGE_ERROR = $TABLE_CREATION_ERROR - 1;
    $DB_REQUEST_ERROR = $CURRENT_DATABASE_CHANGE_ERROR - 1;
